### ISSUE TITLE
Error when adviser rejects course cancellation request from student of course approved by the advisor

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#38]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/sagar/Desktop/bheemboy/coursereg/views/faculty.py", line 255, in participant_advisor_rej
    messages.success(request, 'Rejected the cancellation request of %s.' % req_info)
UnboundLocalError: local variable 'req_info' referenced before assignment
```

**Comment by arthi-ramaniam** [comment]
req_info was not assigned in the 'cancel' case. Fixed.
